services:
  # database
  db:
    image: postgres:18.1-alpine
    container_name: postgres_db
    restart: always
    environment:
      # (wes)chill boys i know this is insecure af but its just for dev purposes before we finalize a .env format
      - POSTGRES_USER=dev_user
      - POSTGRES_PASSWORD=dev_password
      - POSTGRES_DB=forum_db
    ports:
      - "5433:5432"
    volumes:
      # maps local script folder to container auto init folder
      - ./infra/postgres/init-scripts:/docker-entrypoint-initdb.d
      # data persistence, managed by docker volumes
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U dev_user -d forum_db"]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - app_net
    
  logic_hub:
    build:
      context: .
      dockerfile: services/db_service/Dockerfile
    container_name: python_logic_hub
    ports:
      - "8000:8000"
    depends_on:
      db:
        condition: service_healthy
    environment:
      - DATABASE_URL=postgresql+psycopg://dev_user:dev_password@db:5432/forum_db
    networks:
      - app_net

  # add other services below here, example:
  # redis:
  #   image: redis:7-alpine
  #   container_name: redis_cache
  #   ports:
  #     - "6379:6379"

networks:
  app_net:
    driver: bridge

volumes:
  postgres_data: